services:
  web-api:
    image: ${DOCKER_REGISTRY-}webapi
    container_name: web-api
    build:
      context: .
      dockerfile: src/Web.Api/Dockerfile
    networks:
        - icon-network
    ports:
      - 5000:8080
      - 5001:8081

  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    container_name: frontend
    build:
      context: .
      dockerfile: src/frontend/Dockerfile
    networks:
      - icon-network
    ports:
      - 3000:3000


  postgres:
    image: postgres:17
    container_name: postgres
    environment:
      - POSTGRES_DB=icon-architecture
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./.containers/db:/var/lib/postgresql/data
    networks:
        - icon-network
    ports:
      - 5432:5432

  seq:
    image: datalust/seq:2024.3
    container_name: seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 8081:80

networks:
  icon-network:
    driver: bridge
